config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :pizzas
      resources :toppings

      root to: "users#index"
    end
  resources :pizzas
  resources :toppings
  devise_for :users
  root to: "pizzas#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/topping.rb
class Topping < ApplicationRecord
end

app/controllers/admin/toppings_controller.rb
module Admin
  class ToppingsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   foo = Foo.find(params[:id])
    #   foo.update(params[:foo])
    #   send_foo_updated_email
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #  if current_user.super_admin?
    #    resource_class
    #  else
    #    resource_class.with_less_stuff
    #  end
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/toppings_controller.rb
class ToppingsController < ApplicationController
  before_action :authorize_topping
  before_action :set_topping, only: [:show, :edit, :update, :destroy]

  # GET /toppings
  # GET /toppings.json
  def index
    @toppings = Topping.all
  end

  # GET /toppings/1
  # GET /toppings/1.json
  def show
  end

  # GET /toppings/new
  def new
    @topping = Topping.new
  end

  # GET /toppings/1/edit
  def edit
  end

  # POST /toppings
  # POST /toppings.json
  def create
    @topping = Topping.new(topping_params)

    respond_to do |format|
      if @topping.save
        format.html { redirect_to @topping, notice: 'O Sabor foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @topping }
      else
        format.html { render :new }
        format.json { render json: @topping.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /toppings/1
  # PATCH/PUT /toppings/1.json
  def update
    respond_to do |format|
      if @topping.update(topping_params)
        format.html { redirect_to @topping, notice: 'O Sabor foi atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @topping }
      else
        format.html { render :edit }
        format.json { render json: @topping.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /toppings/1
  # DELETE /toppings/1.json
  def destroy
    @topping.destroy
    respond_to do |format|
      format.html { redirect_to toppings_url, notice: 'O Sabor foi destruído com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topping
      @topping = Topping.find(params[:id])

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topping_params
      params.require(:topping).permit(:kind, :price)
     
    end

    def authorize_topping
      authorize Topping
    end
end

app/helpers/toppings_helper.rb
module ToppingsHelper
end

app/views/toppings/_form.html.erb
<%= form_with(model: topping, local: true) do |form| %>
  <% if topping.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(topping.errors.count, "error") %> prohibited this topping from being saved:</h2>

      <ul>
        <% topping.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :kind %>
    <%= form.text_field :kind %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/toppings/edit.html.erb
<h1>Editing Topping</h1>

<%= render 'form', topping: @topping %>

<%= link_to 'Mostrar', @topping %> |
<%= link_to 'Voltar', toppings_path %>

app/views/toppings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sabores</h1>

<table>
  <thead>
    <tr>
      <th>Kind</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @toppings.each do |topping| %>
      <tr>
        <td><%= topping.kind %></td>
        <td><%= topping.price %></td>
        <td><%= link_to 'Mostrar', topping %></td>
        <td><%= link_to 'Editar', edit_topping_path(topping) %></td>
        <td><%= link_to 'Apagar', topping, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Sabor', new_topping_path %>

app/views/toppings/new.html.erb
<h1>New Topping</h1>

<%= render 'form', topping: @topping %>

<%= link_to 'Voltar', toppings_path %>

app/views/toppings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Kind:</strong>
  <%= @topping.kind %>
</p>

<p>
  <strong>Price:</strong>
  <%= @topping.price %>
</p>

<%= link_to 'Editar', edit_topping_path(@topping) %> |
<%= link_to 'Voltar', toppings_path %>