config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :pizzas
      resources :toppings

      root to: "users#index"
    end
  resources :pizzas
  resources :toppings
  devise_for :users
  root to: "pizzas#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/pizza.rb
class Pizza < ApplicationRecord
  belongs_to :topping
  belongs_to :user
  validates :size, presence: true
  validates_inclusion_of :size, :in => 1..3
end

app/controllers/admin/pizzas_controller.rb
module Admin
  class PizzasController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   foo = Foo.find(params[:id])
    #   foo.update(params[:foo])
    #   send_foo_updated_email
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #  if current_user.super_admin?
    #    resource_class
    #  else
    #    resource_class.with_less_stuff
    #  end
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/pizzas_controller.rb
class PizzasController < ApplicationController
  before_action :set_pizza, only: [:show, :edit, :update, :destroy]
  before_action :authorize_pizza, only: [:show, :edit, :update, :destroy]

  # GET /pizzas
  # GET /pizzas.json
  def index
    @pizzas = policy_scope(Pizza).all
  end

  # GET /pizzas/1
  # GET /pizzas/1.json
  def show
  end

  # GET /pizzas/new
  def new
    @pizza = Pizza.new
  end

  # GET /pizzas/1/edit
  def edit
  end

  # POST /pizzas
  # POST /pizzas.json
  def create
    @pizza = Pizza.new(pizza_params)

    respond_to do |format|
      if @pizza.save
        format.html { redirect_to @pizza, notice: 'A Pizza foi criada com sucesso.' }
        format.json { render :show, status: :created, location: @pizza }
      else
        format.html { render :new }
        format.json { render json: @pizza.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pizzas/1
  # PATCH/PUT /pizzas/1.json
  def update
    respond_to do |format|
      if @pizza.update(pizza_params)
        format.html { redirect_to @pizza, notice: 'A Pizza foi atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @pizza }
      else
        format.html { render :edit }
        format.json { render json: @pizza.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pizzas/1
  # DELETE /pizzas/1.json
  def destroy
    @pizza.destroy
    respond_to do |format|
      format.html { redirect_to pizzas_url, notice: 'A Pizza foi destruída com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pizza
      @pizza = Pizza.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pizza_params
      params.require(:pizza).permit(:size, :topping_id).merge(user_id: current_user.id)
    end

    def authorize_pizza
      authorize @pizza
    end
end

app/helpers/pizzas_helper.rb
module PizzasHelper
end

app/views/pizzas/_form.html.erb
<%= form_with(model: pizza, local: true) do |form| %>
  <% if pizza.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pizza.errors.count, "error") %> prohibited this pizza from being saved:</h2>

      <ul>
        <% pizza.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div1><%= form.label :"Tamanho" %></div>
    <%= form.number_field :size %>
  </div>

  <div class="field">
    <%= form.label :"Sabor" %>	
    <%= form.select :topping_id, Topping.all.collect {|m| [ m.kind, m.id ] }, id: :pizza_topping_id %>
  </div>

  <div class="actions">
    <%= form.submit :"Criar Pizza" %>
  </div>
<% end %>

app/views/pizzas/edit.html.erb
<link rel="stylesheet" href="editpizza.css">
<h1>Editar a Pizza</h1>

<%= render 'form', pizza: @pizza %>

<botao>
<%= link_to 'Mostrar', @pizza %> |
<%= link_to 'Voltar', pizzas_path %>
</botao>

app/views/pizzas/index.html.erb
<!doctype html>
<html>  
  <link rel="stylesheet" href="style.css">
  <p id="notice"><%= notice %></p>
<head>
</head>
<body>
  <center>
    <h1>Pizzas</h1>

    <table>
      <thead>
        <tr>
          <titulos1><th>Tamanho</th></titulos1>
          <titulos2><th>Sabor</th></titulos2>
          <titulos3><th>Usuário</th></titulos3>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @pizzas.each do |pizza| %>
          <tr>
            <atributos><td><%= pizza.size %></td></atributos>
            <td><%= pizza.topping.kind %></td>
            <td><%= pizza.user.email %></td>
            <td><%= link_to 'Mostrar', pizza %></td>
            <td><%= link_to 'Editar', edit_pizza_path(pizza) %></td>
            <td><%= link_to 'Apagar', pizza, method: :delete, data: { confirm: 'Tem Certeza?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <newpizza><%= link_to 'Nova Pizza', new_pizza_path %></newpizza>
</body>
</html>

app/views/pizzas/new.html.erb
<h1>Nova Pizza</h1>

<%= render 'form', pizza: @pizza %>

<%= link_to 'Voltar', pizzas_path %>

app/views/pizzas/show.html.erb
<p id="notice"><%= notice %></p>
<link rel="stylesheet" href="showpizza.css">
<p>
  <strong>Tamanho:</strong>
  <%= @pizza.size %>
</p>

<p>
  <strong>Sabor:</strong>
  <%= @pizza.topping.kind %>
</p>

<p>
  <strong>Usuário:</strong>
  <%= @pizza.user.email %>
</p>
<botao>
<%= link_to 'Editar', edit_pizza_path(@pizza) %> |
<%= link_to 'Voltar', pizzas_path %>
</botao>